services:
  tw_stock_tools:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: nk7260ynpa/tw_stock_tools:latest
    container_name: tw_stock_tools
    ports:
      - "8000:8000"
    volumes:
      - ../logs:/app/logs
    environment:
      - PYTHONPATH=/app/src
